import { NextRequest, NextResponse } from 'next/server';
import { verifyAdmin } from '@/lib/authUtils';
import prisma from '@/lib/db';

export async function GET(
  request: NextRequest,
  { params }: { params: { reportId: string } }
) {
  try {
    // Check authentication and authorization
    if (!await verifyAdmin(request)) {
      return NextResponse.json(
        { error: 'Unauthorized or forbidden' },
        { status: 403 }
      );
    }
    
    const reportId = params.reportId;
    
    if (!reportId) {
      return NextResponse.json(
        { error: 'Report ID is required' },
        { status: 400 }
      );
    }
    
    // Fetch the report from the database
    const report = await prisma.report.findUnique({
      where: {
        id: reportId
      }
    });
    
    if (!report) {
      return NextResponse.json(
        { error: 'Report not found' },
        { status: 404 }
      );
    }
    
    // Check if the report is available
    if (report.status !== 'available') {
      return NextResponse.json(
        { error: 'Report is not available for download yet' },
        { status: 400 }
      );
    }
    
    // In a real implementation, you would fetch the actual report data from a file storage
    // or generate it dynamically based on stored parameters
    
    // For this implementation, we'll create a simple text report
    const reportDate = new Date().toLocaleDateString();
    const reportTime = new Date().toLocaleTimeString();
    
    // Fetch some real data based on report type
    let reportData = '';
    
    switch (report.type) {
      case 'financial':
        const orders = await prisma.order.findMany({
          take: 10,
          orderBy: {
            createdAt: 'desc'
          },
          select: {
            id: true,
            totalAmount: true,
            status: true,
            createdAt: true
          }
        });
        
        reportData = `Financial Summary:\n\n`;
        reportData += `Total Orders: ${orders.length}\n`;
        reportData += `Total Revenue: $${orders.reduce((sum, order) => sum + order.totalAmount, 0).toFixed(2)}\n\n`;
        reportData += `Recent Orders:\n`;
        
        orders.forEach(order => {
          reportData += `- Order ${order.id}: $${order.totalAmount.toFixed(2)} (${order.status}) - ${new Date(order.createdAt).toLocaleDateString()}\n`;
        });
        break;
        
      case 'analytics':
        const visitors = await prisma.visitor.count();
        const conversions = await prisma.conversion.findMany({
          take: 10,
          orderBy: {
            date: 'desc'
          }
        });
        
        const totalAttempts = conversions.reduce((sum, conv) => sum + conv.attempts, 0);
        const totalConversions = conversions.reduce((sum, conv) => sum + conv.conversions, 0);
        const conversionRate = totalAttempts > 0 ? (totalConversions / totalAttempts) * 100 : 0;
        
        reportData = `Analytics Summary:\n\n`;
        reportData += `Total Visitors: ${visitors}\n`;
        reportData += `Conversion Rate: ${conversionRate.toFixed(2)}%\n\n`;
        reportData += `Recent Conversion Data:\n`;
        
        conversions.forEach(conv => {
          reportData += `- Date ${new Date(conv.date).toLocaleDateString()}: ${conv.conversions} conversions out of ${conv.attempts} attempts (${((conv.conversions / conv.attempts) * 100).toFixed(2)}%)\n`;
        });
        break;
        
      default:
        reportData = `${report.type.charAt(0).toUpperCase() + report.type.slice(1)} Report\n\n`;
        reportData += `This is a generated report based on the ${report.type} type.\n`;
        reportData += `More specific data would be included in a real implementation.\n`;
    }
    
    const reportContent = `
Report ID: ${reportId}
Title: ${report.title}
Type: ${report.type}
Generated: ${reportDate} at ${reportTime}
---------------------------------------------

${reportData}

---------------------------------------------
Report generated by NextGenRDP Admin System
    `;
    
    // Create headers for file download
    const headers = new Headers();
    headers.set('Content-Type', 'text/plain');
    headers.set('Content-Disposition', `attachment; filename="report-${reportId}.txt"`);
    
    // Update the download count
    await prisma.report.update({
      where: { id: reportId },
      data: {
        downloadCount: {
          increment: 1
        },
        lastDownloaded: new Date()
      }
    });
    
    return new NextResponse(reportContent, {
      status: 200,
      headers,
    });
  } catch (error) {
    console.error('Error downloading report:', error);
    
    return NextResponse.json(
      { error: 'Failed to download report' },
      { status: 500 }
    );
  }
} 